{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.mediarouter",
    "module": "mediarouter",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "7441664"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mediarouter-1.2.4.aar",
          "url": "mediarouter-1.2.4.aar",
          "size": 748163,
          "sha512": "2655bc696fdc3e59e4a3ebd3f8687067cc2d20332ba4110d9824d06d08e294c7ceed0fa26e5fa5cef5b08ffadef176dc3e0f33bbba2c8edf12f611c16cf36c2f",
          "sha256": "c9c13aa36be3f8160be9425c13489c7fed45844cfc1f7fcb00acf3982de8a436",
          "sha1": "5739c830492d3220523b6558360795fb64706700",
          "md5": "3de34d38900e20811fd435e9952416a9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mediarouter-1.2.4.aar",
          "url": "mediarouter-1.2.4.aar",
          "size": 748163,
          "sha512": "2655bc696fdc3e59e4a3ebd3f8687067cc2d20332ba4110d9824d06d08e294c7ceed0fa26e5fa5cef5b08ffadef176dc3e0f33bbba2c8edf12f611c16cf36c2f",
          "sha256": "c9c13aa36be3f8160be9425c13489c7fed45844cfc1f7fcb00acf3982de8a436",
          "sha1": "5739c830492d3220523b6558360795fb64706700",
          "md5": "3de34d38900e20811fd435e9952416a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mediarouter-1.2.4-sources.jar",
          "url": "mediarouter-1.2.4-sources.jar",
          "size": 193568,
          "sha512": "79961b20872a0857a551ffcc875d6f03ae9c546e0f460bbb0297a47e1189fb590ef7b59f77c12933d5fa388cf782539eca1e4d8da7bdffbfb38ade03c8bbcb68",
          "sha256": "5dcf3c54750f5e13939efb44cfa20f781d222e6977558feec00660d887021177",
          "sha1": "c4091091fe922eedf3f20b2ba0927b946a14f740",
          "md5": "0dec1c1e74b45203f4724c5112dc56ca"
        }
      ]
    }
  ]
}
